version: '3'

services:
  discord-bot:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - CONFIG_PATH=/app/data/config.json
      - LOG_FILE=/app/data/access_attempts.log
    restart: unless-stopped
    container_name: discord-id-protector
